"""ADD mobile colimn

Revision ID: 480cded579ab
Revises: 76cfe2c48770
Create Date: 2024-09-08 02:13:52.820840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480cded579ab'
down_revision = '76cfe2c48770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=11), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###
